name: Check Version

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  check-package-json-changes:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for package.json changes
        run: |
          changes=$(git diff origin/main origin/${{ github.event.pull_request.head.ref }} -- package.json | grep 'version')
          if ! "$changes"; then
            echo "version is not changed"
            exit 1
          else
            echo "version is changed"
          fi

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          check-latest: true
